//! Hook installation into fresh/existing/worktree/framework-owned repos and hooks-dir resolution.

use super::*;

/// The core behavior change: a framework-owned repo (signaled by a
/// present `.pre-commit-config.yaml`) gets its `pre-commit` entry
/// redirected to the YAML, never spliced into the raw hook file —
/// while every OTHER managed hook still installs normally.
#[test]
fn install_redirects_precommit_to_yaml_when_framework_owned() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_repo(root);
    seed_commit(root);
    std::fs::write(
        root.join(".pre-commit-config.yaml"),
        "repos:\n  - repo: https://github.com/psf/black\n    rev: 24.0\n",
    )
    .unwrap();

    install(root).unwrap();

    let hooks_dir = root.join(".git").join("hooks");
    let raw_precommit = std::fs::read_to_string(hooks_dir.join("pre-commit")).unwrap_or_default();
    assert!(
        !raw_precommit.contains(MARKER_START),
        "must NOT splice into the raw file when framework-owned: {raw_precommit}"
    );

    let yaml = std::fs::read_to_string(root.join(".pre-commit-config.yaml")).unwrap();
    assert!(yaml.contains("entry: rsry hooks run pre-commit"), "{yaml}");
    assert!(
        yaml.contains("psf/black"),
        "pre-existing entry lost: {yaml}"
    );

    // Every OTHER hook is unaffected — still gets the normal raw-file
    // treatment.
    let post_push = std::fs::read_to_string(hooks_dir.join("post-push")).unwrap();
    assert!(post_push.contains(MARKER_START));
}

/// Regression pin: an ordinary (non-framework) repo is completely
/// unaffected by this bead — ensures the new detection didn't
/// change existing behavior for the common case.
#[test]
fn install_still_uses_raw_file_when_not_framework_owned() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_repo(root);
    seed_commit(root);

    install(root).unwrap();

    let raw_precommit = std::fs::read_to_string(root.join(".git/hooks/pre-commit")).unwrap();
    assert!(raw_precommit.contains(MARKER_START));
    assert!(!root.join(".pre-commit-config.yaml").exists());
}

/// The fallback signal: no `.pre-commit-config.yaml` at all, but the
/// EXISTING raw hook already shows the framework's generated shape
/// (the exact live signature observed in mache). `install()` must
/// still redirect — and since no config file existed, creates a
/// minimal one rather than erroring.
#[test]
fn install_detects_framework_ownership_via_existing_hook_marker() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_repo(root);
    seed_commit(root);
    let hooks_dir = root.join(".git").join("hooks");
    std::fs::create_dir_all(&hooks_dir).unwrap();
    std::fs::write(
        hooks_dir.join("pre-commit"),
        "#!/usr/bin/env bash\n\
         # File generated by pre-commit: https://pre-commit.com\n\
         # ID: 138fd403232d2ddd5efb44317e38bf03\n\
         exec pre-commit hook-impl --hook-type=pre-commit \"$@\"\n",
    )
    .unwrap();

    install(root).unwrap();

    let yaml = std::fs::read_to_string(root.join(".pre-commit-config.yaml")).unwrap();
    assert!(yaml.contains("entry: rsry hooks run pre-commit"), "{yaml}");
    assert!(yaml.starts_with("repos:\n"), "{yaml}");
}

/// The acceptance criterion, directly: simulate a fresh
/// `pre-commit install` regenerating `.git/hooks/pre-commit` from
/// scratch AFTER rsry's install ran. `.pre-commit-config.yaml` is a
/// separate file regeneration never touches — this proves rsry's
/// check survives, rather than asserting anything about pre-commit's
/// own dispatch (which would require the real `pre-commit` binary).
#[test]
fn precommit_yaml_survives_a_simulated_framework_regeneration() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_repo(root);
    seed_commit(root);
    std::fs::write(root.join(".pre-commit-config.yaml"), "repos: []\n").unwrap();

    install(root).unwrap();
    let after_install = std::fs::read_to_string(root.join(".pre-commit-config.yaml")).unwrap();
    assert!(after_install.contains("entry: rsry hooks run pre-commit"));

    // Simulate `pre-commit install` regenerating the raw hook file —
    // the exact framework-only shape observed live, zero rsry
    // markers.
    let hooks_dir = root.join(".git").join("hooks");
    std::fs::write(
        hooks_dir.join("pre-commit"),
        "#!/usr/bin/env bash\n\
         # File generated by pre-commit: https://pre-commit.com\n\
         exec pre-commit hook-impl --hook-type=pre-commit \"$@\"\n",
    )
    .unwrap();
    let regenerated = std::fs::read_to_string(hooks_dir.join("pre-commit")).unwrap();
    assert!(
        !regenerated.contains(MARKER_START),
        "sanity: regeneration must genuinely wipe any rsry markers, \
         or this test would prove nothing"
    );

    let after_regeneration = std::fs::read_to_string(root.join(".pre-commit-config.yaml")).unwrap();
    assert_eq!(
        after_install, after_regeneration,
        "the YAML fix must be untouched by raw-hook-file regeneration"
    );
}

#[test]
fn resolve_hooks_dir_regular_repo() {
    let dir = tempfile::tempdir().unwrap();
    init_repo(dir.path());
    let resolved = resolve_hooks_dir(dir.path()).unwrap();
    // Canonicalize to avoid symlink-prefix mismatches on macOS
    // (/var vs /private/var).
    assert_eq!(
        resolved.canonicalize().unwrap(),
        dir.path()
            .canonicalize()
            .unwrap()
            .join(".git")
            .join("hooks")
    );
}

#[test]
fn resolve_hooks_dir_worktree() {
    // Main repo with a seed commit, then `git worktree add` a sibling.
    // Inside the worktree, `.git` is a FILE pointing at the gitdir —
    // the old `repo_root.join(".git").join("hooks")` shortcut would
    // produce a non-existent path here.
    let main = tempfile::tempdir().unwrap();
    init_repo(main.path());
    seed_commit(main.path());

    let wt_parent = tempfile::tempdir().unwrap();
    let wt_path = wt_parent.path().join("wt");
    assert!(
        git(
            main.path(),
            &[
                "worktree",
                "add",
                "-q",
                "-b",
                "wt-branch",
                wt_path.to_str().unwrap(),
            ],
        )
        .status
        .success(),
        "git worktree add must succeed",
    );

    // Sanity: in a worktree, .git is a file (not a directory).
    assert!(wt_path.join(".git").is_file());

    let resolved = resolve_hooks_dir(&wt_path).unwrap();
    // The resolved path must NOT be wt_path/.git/hooks (which doesn't
    // exist as a directory in a worktree). It should point under the
    // main gitdir or a worktree-specific hooks dir, but in any case
    // the canonicalized prefix should be the main repo's gitdir.
    let main_gitdir = main.path().canonicalize().unwrap().join(".git");
    assert!(
        resolved
            .canonicalize()
            .or_else(|_| resolved.parent().unwrap().canonicalize())
            .unwrap()
            .starts_with(&main_gitdir),
        "worktree hooks dir {} should be under main gitdir {}",
        resolved.display(),
        main_gitdir.display(),
    );
}

#[test]
fn resolve_hooks_dir_non_git_errors() {
    let dir = tempfile::tempdir().unwrap();
    // Empty tempdir, no git init — must fail loudly.
    let err = resolve_hooks_dir(dir.path()).unwrap_err();
    assert!(
        err.to_string().contains("not a git repo"),
        "expected `not a git repo` in error, got: {err}",
    );
}

#[test]
fn install_merges_into_existing_user_hook() {
    let dir = tempfile::tempdir().unwrap();
    init_repo(dir.path());
    let hooks_dir = dir.path().join(".git").join("hooks");
    std::fs::create_dir_all(&hooks_dir).unwrap();
    let post_push = hooks_dir.join("post-push");
    // Simulate a pre-existing user hook with custom logic.
    std::fs::write(
        &post_push,
        "#!/bin/sh\n# team-managed hook\necho 'user custom logic'\n",
    )
    .unwrap();

    install(dir.path()).unwrap();

    let content = std::fs::read_to_string(&post_push).unwrap();
    assert!(
        content.contains("user custom logic"),
        "user logic must be preserved across install: {content}",
    );
    assert!(content.contains(MARKER_START));
    assert!(content.contains(MARKER_END));
    assert!(content.contains("team-managed hook"));
}

#[test]
fn install_idempotent_on_reinstall() {
    let dir = tempfile::tempdir().unwrap();
    init_repo(dir.path());
    install(dir.path()).unwrap();
    let path = dir.path().join(".git").join("hooks").join("post-push");
    let first = std::fs::read_to_string(&path).unwrap();
    // Reinstall — should produce identical bytes (no duplicated block).
    install(dir.path()).unwrap();
    let second = std::fs::read_to_string(&path).unwrap();
    assert_eq!(first, second, "reinstall should be idempotent");
    assert_eq!(
        second.matches(MARKER_START).count(),
        1,
        "no duplicated rsry block on reinstall",
    );
}

#[test]
fn install_preserves_user_content_after_marker_section() {
    let dir = tempfile::tempdir().unwrap();
    init_repo(dir.path());
    // First install lays down the rsry block.
    install(dir.path()).unwrap();
    let path = dir.path().join(".git").join("hooks").join("post-push");
    // User appends their own logic AFTER the rsry marker block.
    let original = std::fs::read_to_string(&path).unwrap();
    std::fs::write(&path, format!("{}\necho 'user trailer'\n", original)).unwrap();

    // Reinstall — must preserve the user trailer.
    install(dir.path()).unwrap();
    let after = std::fs::read_to_string(&path).unwrap();
    assert!(
        after.contains("user trailer"),
        "user trailer dropped: {after}"
    );
    assert!(after.contains(MARKER_START));
}

#[test]
fn install_works_in_git_worktree() {
    // The bug Copilot caught: in a worktree, `.git` is a file pointer
    // and `.git/hooks/` doesn't exist. Old code bailed with "is this a
    // git repo?" — new code routes through `git rev-parse` and writes
    // to the right place.
    let main = tempfile::tempdir().unwrap();
    init_repo(main.path());
    seed_commit(main.path());
    let wt_parent = tempfile::tempdir().unwrap();
    let wt_path = wt_parent.path().join("wt");
    assert!(
        git(
            main.path(),
            &[
                "worktree",
                "add",
                "-q",
                "-b",
                "wt-install",
                wt_path.to_str().unwrap(),
            ],
        )
        .status
        .success()
    );

    install(&wt_path).expect("install must succeed in a worktree");

    // The hook landed somewhere reachable via resolve_hooks_dir.
    let hooks_dir = resolve_hooks_dir(&wt_path).unwrap();
    for (name, _) in HOOKS {
        assert!(
            hooks_dir.join(name).exists(),
            "{name} should be installed at {}",
            hooks_dir.display(),
        );
    }
}

#[test]
fn install_errors_outside_git_repo() {
    let dir = tempfile::tempdir().unwrap();
    // No git init — install must refuse rather than write into a
    // random directory.
    let err = install(dir.path()).unwrap_err();
    assert!(
        err.to_string().contains("not a git repo"),
        "expected error mentioning `not a git repo`, got: {err}",
    );
}

#[test]
fn install_into_fresh_repo() {
    let dir = tempfile::tempdir().unwrap();
    init_repo(dir.path());
    install(dir.path()).unwrap();
    for (name, block) in HOOKS {
        let path = dir.path().join(".git").join("hooks").join(name);
        assert!(path.exists(), "{name} should be installed");
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("#!/bin/sh"));
        assert!(content.contains(MARKER_START));
        assert!(content.contains(MARKER_END));
        let rendered = render_managed_block(name, block);
        assert!(
            content.contains(rendered.trim()),
            "{name} should contain rendered template content",
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o755, "{name} should be executable (0o755)");
        }
    }
}
