//! Pure logic for detecting a pre-commit-framework-owned repo and editing
//! `.pre-commit-config.yaml` — no filesystem or subprocess calls, so it's
//! directly mutation-testable in isolation (`task mutants:precommit_yaml`,
//! rosary-00f2b5). The I/O side (reading the real files, deciding when to
//! call this at all, running `rsry hooks run`) lives in `mod hooks`
//! (`src/main.rs`).

/// Is this repo's `pre-commit` hook owned by the Python pre-commit framework
/// rather than a plain shell script? Either signal is sufficient —
/// `pre_commit_config_exists` is the durable one (present even before a
/// first `pre-commit install`); the marker in `existing_hook_content` is the
/// fallback for a repo whose config isn't visible to this check (e.g.
/// gitignored) but whose raw hook file already shows the framework's own
/// generated shape.
pub(crate) fn is_precommit_framework_owned(
    pre_commit_config_exists: bool,
    existing_hook_content: Option<&str>,
) -> bool {
    pre_commit_config_exists
        || existing_hook_content
            .map(|c| c.contains("File generated by pre-commit: https://pre-commit.com"))
            .unwrap_or(false)
}

/// Begin/end markers for the block `hooks install` splices into
/// `.pre-commit-config.yaml` — distinct from the shell-hook markers in
/// `mod hooks` (those wrap a *hook file*; this wraps a *YAML list item*, so
/// it needs its own comment indentation to stay valid YAML).
const PRECOMMIT_YAML_MARKER_START: &str = "  # >>> rsry-managed (do not edit between these markers; `rsry hooks install` regenerates) >>>";
const PRECOMMIT_YAML_MARKER_END: &str = "  # <<< rsry-managed <<<";

/// The `repo: local` entry rsry adds to `.pre-commit-config.yaml`.
/// Deliberately its own dedicated entry rather than merged into an existing
/// `local` repo, if the file already has one — pre-commit's schema
/// explicitly permits multiple `repo: local` entries in one file, and
/// text-surgically merging INTO an unknown existing entry's `hooks:` list is
/// a much harder, more fragile problem than appending a whole new one.
/// `entry:` names the STABLE `rsry hooks run pre-commit` command, never
/// inlined shell — that is the whole point: an `rsry` upgrade changes the
/// check without ever touching this file.
pub(crate) fn precommit_yaml_entry() -> String {
    format!(
        "{PRECOMMIT_YAML_MARKER_START}\n\
         \x20 - repo: local\n\
         \x20   hooks:\n\
         \x20     - id: rsry-bead-sync\n\
         \x20       name: rsry bead export sync (rosary-00f2b5)\n\
         \x20       entry: rsry hooks run pre-commit\n\
         \x20       language: system\n\
         \x20       pass_filenames: false\n\
         \x20       always_run: true\n\
         \x20       stages: [pre-commit]\n\
         {PRECOMMIT_YAML_MARKER_END}\n"
    )
}

/// Idempotently insert or update rsry's marked block in a
/// `.pre-commit-config.yaml`'s content. Text-surgical, not a YAML
/// parse+reserialize — a generic YAML round-trip commonly reformats
/// style/quoting and can drop comments, an unacceptable diff on a file
/// developers hand-edit and review. Everything outside the markers is
/// preserved byte-for-byte.
///
/// An existing marked block is replaced in place (reinstall converges).
/// Otherwise the new block is inserted immediately after the top-level
/// `repos:` line — position within the list doesn't affect correctness, and
/// this avoids needing to find the "right" place among entries of unknown
/// shape. A file with no `repos:` key at all gets one created (pre-commit
/// requires it; a `.pre-commit-config.yaml` without it is already broken
/// independent of rsry).
pub(crate) fn merge_precommit_yaml(existing: &str) -> String {
    if let Some(start) = existing.find(PRECOMMIT_YAML_MARKER_START) {
        let after_start = start + PRECOMMIT_YAML_MARKER_START.len();
        let end = existing[after_start..]
            .find(PRECOMMIT_YAML_MARKER_END)
            .map(|offset| after_start + offset + PRECOMMIT_YAML_MARKER_END.len())
            .unwrap_or(existing.len());
        let mut out = String::with_capacity(existing.len());
        out.push_str(&existing[..start]);
        out.push_str(&precommit_yaml_entry());
        out.push_str(existing[end..].trim_start_matches('\n'));
        return out;
    }

    let mut out = String::with_capacity(existing.len() + 256);
    let mut inserted = false;
    for line in existing.lines() {
        out.push_str(line);
        out.push('\n');
        if !inserted && line.trim_end() == "repos:" {
            out.push_str(&precommit_yaml_entry());
            inserted = true;
        }
    }
    if !inserted {
        out.push_str("repos:\n");
        out.push_str(&precommit_yaml_entry());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_precommit_framework_owned_true_when_config_exists() {
        assert!(is_precommit_framework_owned(true, None));
    }

    #[test]
    fn is_precommit_framework_owned_true_via_generated_marker() {
        let content =
            "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n";
        assert!(is_precommit_framework_owned(false, Some(content)));
    }

    #[test]
    fn is_precommit_framework_owned_false_when_neither_signal() {
        assert!(!is_precommit_framework_owned(false, None));
        assert!(!is_precommit_framework_owned(
            false,
            Some("#!/bin/sh\necho hi\n")
        ));
    }

    #[test]
    fn is_precommit_framework_owned_config_signal_wins_even_with_plain_hook_content() {
        // The two signals are independent ORs — a plain-looking hook file
        // must not suppress the config-file signal.
        assert!(is_precommit_framework_owned(
            true,
            Some("#!/bin/sh\necho hi\n")
        ));
    }

    #[test]
    fn precommit_yaml_entry_names_the_stable_run_command() {
        let entry = precommit_yaml_entry();
        assert!(entry.contains("entry: rsry hooks run pre-commit"));
        assert!(entry.contains("repo: local"));
        assert!(entry.contains("language: system"));
        assert!(entry.contains("always_run: true"));
    }

    #[test]
    fn merge_precommit_yaml_inserts_after_repos_key() {
        let existing = "repos:\n  - repo: https://github.com/psf/black\n    rev: 1.0\n";
        let out = merge_precommit_yaml(existing);
        assert!(out.starts_with("repos:\n"));
        assert!(out.contains("entry: rsry hooks run pre-commit"));
        assert!(out.contains("https://github.com/psf/black"), "{out}");
        // The inserted block comes before the pre-existing entry, since it
        // is spliced immediately after the `repos:` line.
        assert!(
            out.find("entry: rsry hooks run pre-commit").unwrap() < out.find("psf/black").unwrap()
        );
    }

    #[test]
    fn merge_precommit_yaml_creates_repos_key_when_absent() {
        let existing = "# empty config\n";
        let out = merge_precommit_yaml(existing);
        assert!(out.contains("repos:\n"));
        assert!(out.contains("entry: rsry hooks run pre-commit"));
    }

    #[test]
    fn merge_precommit_yaml_is_idempotent_on_reinstall() {
        let existing = "repos:\n  - repo: https://github.com/psf/black\n    rev: 1.0\n";
        let once = merge_precommit_yaml(existing);
        let twice = merge_precommit_yaml(&once);
        assert_eq!(once, twice, "reinstall must converge, not duplicate");
        assert_eq!(twice.matches("entry: rsry hooks run pre-commit").count(), 1);
    }

    #[test]
    fn merge_precommit_yaml_preserves_content_outside_markers() {
        let existing = "repos:\n  - repo: https://github.com/psf/black\n    rev: 1.0\n    hooks:\n      - id: black\n";
        let out = merge_precommit_yaml(existing);
        assert!(out.contains("- id: black"), "{out}");
        assert!(out.contains("rev: 1.0"), "{out}");
    }
}
